#!/bin/bash

BUILD_ARCH=$(echo "${DOCKERFILE_PATH}" | rev | cut -d '.' -f 2 | rev)

echo "$(echo "${DOCKER_TAG}" | cut -d '-' -f 2 | rev | cut -d '-' -f 2 | rev)"

docker build \
    --compress \
    --pull \
    --file "${DOCKERFILE_PATH}" \
    --build-arg BUILD_DATE="$(date -u +"%Y-%m-%dT%H:%M:%SZ")" \
    --build-arg VCS_REF="$(git rev-parse --short HEAD)" \
    --build-arg ROS_DISTRO=eloquent \
    --build-arg DOCKER_REPO="${DOCKER_REPO}" \
    --build-arg DOCKERHUB_NAME=ros2cuisine \
    --build-arg ROS_DISTRO=eloquent \
    --build-arg BUILD_REPO=ubuntu \
    --build-arg BUILD_VERSION=bionic \
    --build-arg BUILD_ARCH=$(echo "${DOCKER_TAG}" | cut -d '-' -f 2 | rev | cut -d '-' -f 2 | rev) \
    --tag "${IMAGE_NAME}" \
    .
