#!/bin/bash
apt-get update && apt-get install curl wget git bash -y -q

wget https://raw.githubusercontent.com/ichbestimmtnicht/docker-autobuild-release/master/hooks/post_checkout

bash post_checkout
