#!/bin/bash

# https://github.com/ichbestimmtnicht/docker-autobuild-release
# Created 2020 by Ludwig Werner Döhnert
# This work is licensed under the Creative Commons Attribution 4.0 International License.
# To view a copy of this license, visit http://creativecommons.org/licenses/by/4.0/.

apt-get update && apt-get install curl wget git bash -y -q

wget https://raw.githubusercontent.com/ichbestimmtnicht/docker-autobuild-release/master/hooks/post_checkout

bash post_checkout

exit 0
