#!/bin/bash
echo "Disable standardpush"
apt-get update && apt-get install wget -y -q

cat auto-docker-manifest.yaml

# Get the manifest-tool
wget -cO - https://github.com/estesp/manifest-tool/releases/download/v1.0.0/manifest-tool-linux-arm64 /bin/ > manifest-tool

chmod +x /bin/manifest-tool
# Push the docker image
./manifest-tool push from-spec distro-manifest.yaml
rm -f distro-manifest.yaml

# Push the completed tag
